# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be3f8f92d6601d7ef8d61448485db534253e11c9f3b791c8a93364bb6233e2ee5307983416f0eb6504881d1601a02e3990e860609b1fba004587936b488d1931

test:
  secret_key_base: 7483adf715f26a170adbd8ffe7210e9af90e3b090a5b718d116954b634481f33f222e92efdb9193086f1397f42b0608c510926f6d91c2acb005460dea4a9f41f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
